### ISSUE TITLE
[FEAT] 여행 일정 삭제 API 연결

### ISSUE THREAD

**Issue by Taehyeon-Kim** [TeamDooRiBon/DooRi-iOS#113]
# 👀 이슈 (issue)

여행 일정 삭제 API를 연결합니다.
<img width="250" alt="스크린샷 2021-07-15 오후 12 07 31" src="https://user-images.githubusercontent.com/61109660/125721841-cd449fea-613f-494d-adee-7d923004e476.png">

# 🚀 to-do

- [x] postman 요청 확인
- [x] url constants (있으면 생략)
- [x] data model (있으면 생략)
- [x] service (있으면 생략)
