### ISSUE TITLE
[FEAT] 여행 보드 삭제 API 연결

### ISSUE THREAD

**Issue by Taehyeon-Kim** [TeamDooRiBon/DooRi-iOS#115]
# 👀 이슈 (issue)

여행 보드 삭제 API를 연결합니다.

# 🚀 to-do

- [x] postman 테스트
- [x] 데이터 모델 생성
- [x] 서비스 코드 작성
- [x] 네트워크 통신 테스트
