### ISSUE TITLE
[FIX] 미션 구현 및 이슈 해결

### ISSUE THREAD

**Issue by Taehyeon-Kim** [TeamDooRiBon/DooRi-iOS#118]
# 👀 이슈 (issue)

일차적인 이슈 해결과 미션을 구현합니다.

# 🚀 to-do

- [x] skeleton UI (데이터 로드 중에 표시될 UI)
- [x] Toast Hide 애니메이션 변경
- [x] 여행 일정 뷰에서 기간 표시 이슈 해결 (첫날 ~ 마지막날 date 계산)
