### ISSUE TITLE
[ADD] 여행 추가 입력 뷰

### ISSUE THREAD

**Issue by Hansangjin98** [TeamDooRiBon/DooRi-iOS#12]
# 👀 이슈 (issue)

'새로운 여행 추가'에 관련된 뷰 입니다.

# 🚀 to-do

- [x] 스크롤 뷰 셋팅
- [x] 여행 이름 입력 필드 셋팅
- [x] 여행 장소 입력 필드 셋팅
- [x] 여행 일정 등록 필드 셋팅
- [x] 대표 사진 선택 필드 (컬렉션 뷰) 셋팅
