### ISSUE TITLE
[FEAT] 여행 일정 뷰 상단 고정 영역 + 캘린더 포함

### ISSUE THREAD

**Issue by Taehyeon-Kim** [TeamDooRiBon/DooRi-iOS#13]
# 👀 이슈 (issue)

캘린더가 있는 여행일정뷰 상단 고정영역에 대해서 레이아웃을 구혀하려고 합니다.
<img width="367" alt="스크린샷 2021-07-02 오전 11 51 53" src="https://user-images.githubusercontent.com/61109660/124225979-4d3bf980-db43-11eb-9fc0-49d9dd6acbe0.png">

# 🚀 to-do

- [ ] 캘린더 상단 영역 레이아웃 잡기
- [ ] 캘린더 날짜 계산
- [ ] 캘린더 년도, 월 영역 수직 스크롤
- [ ] 캘린더 일 영역 수평 스크롤
