### ISSUE TITLE
[BUG] 여행 일정 확인 뷰 버그 수정

### ISSUE THREAD

**Issue by Taehyeon-Kim** [TeamDooRiBon/DooRi-iOS#182]
# 👀 이슈 (issue)

여행 일정 확인 뷰에서 발생하는 버그를 수정합니다.

# 🚀 to-do

- [ ] 시작 시 년도, 월 세팅
- [ ] 테이블 셀 헤더 부분 데이터 변경
- [ ] 로딩 속도 문제: 인디케이터를 거는 방식으로
- [ ] 날짜 셀 클릭했을 때 컨텐츠 데이터 변경
