### ISSUE TITLE
[FEAT] 여행 참여 코드 입력 뷰 구현

### ISSUE THREAD

**Issue by Taehyeon-Kim** [TeamDooRiBon/DooRi-iOS#21]
# 👀 이슈 (issue)

여행 추가 카테고리에 있는 여행 참여 코드 입력 뷰를 구현합니다.
<img width="398" alt="스크린샷 2021-07-02 오후 4 43 06" src="https://user-images.githubusercontent.com/61109660/124344660-9f961c80-dc0e-11eb-9184-5d328b789040.png">

# 🚀 to-do

- [x] 레이아웃 구성
- [x] viewDidLoad 시 텍스트필드 포커스 및 키보드 활성화
- [x] 입력칸 활성화 시 색상 또는 이미지 변경
- [x] 글자 수 제한 (한 칸에 숫자 하나씩)
- [x] 입력후에는 다음칸 활성화
- [x] 코드 전부 입력되었을때는 전체칸 활성화 및 버튼 활성화
- [x] 코드 지울때마다 이전칸으로 포커스 이동
- [ ] #30

# 💬 코멘트 (comment)

`혜진's comment` : 코드 입력은 canBecomeFirstResponder 요거 한번 찾아보기 
**코멘트 주신대로 한 번 찾아보겠습니다.**
