### ISSUE TITLE
[FEAT] 여행일정뷰 하단 컨텐츠 영역 구현

### ISSUE THREAD

**Issue by Taehyeon-Kim** [TeamDooRiBon/DooRi-iOS#45]
# 👀 이슈 (issue)
- 여행일정뷰 남은 부분에 대한 작업을 진행합니다.
<img width="200" alt="스크린샷 2021-07-07 오후 4 39 53" src="https://user-images.githubusercontent.com/61109660/124719608-4b5aa780-df42-11eb-9615-f18aed78eb6e.png"> <img width="200" alt="스크린샷 2021-07-07 오후 4 40 05" src="https://user-images.githubusercontent.com/61109660/124719617-4dbd0180-df42-11eb-9e9a-279dafe48966.png">

# 🚀 to-do

- [x] 일정 없을때 뷰
- [x] 일정 하나 추가
- [x] 일정 여러 개
- [x] 일정뷰 데이터 모델
- [ ] 일정정보 바텀시트
- [ ] 일정삭제 팝업 연결
- [ ] 참여코드 복사 토스트
