### ISSUE TITLE
[FEAT] 메인 뷰→여행 추가 뷰 연결

### ISSUE THREAD

**Issue by Hansangjin98** [TeamDooRiBon/DooRi-iOS#60]
# 👀 이슈 (issue)

메인 뷰와 여행 추가 뷰를 연결합니다.

# 🚀 to-do

- [ ] 메인뷰 팝업 참여-시작 오타 수정
- [ ] 메인뷰 팝업 버튼 터치 영역 수정
- [ ] 여행 추가 뷰 연결
