### ISSUE TITLE
[FEAT] 여행 테스트 답변선택 부분

### ISSUE THREAD

**Issue by mini-min** [TeamDooRiBon/DooRi-iOS#64]
# 👀 이슈 (issue)

여행 테스트 답변선택 부분을 구현했습니다.

# 🚀 to-do

- [ ] 문항선택 테이블뷰
- [x] 문제 10개 컬렉션뷰
- [x] 프로그레스바
- [ ] 다음으로 넘어가는 버튼
- [ ] 이전으로 돌아가는 버튼
- [ ] 테스트 완료 팝업
- [x] 중도 포기 팝업
