### ISSUE TITLE
[CHORE] 폰트 세팅

### ISSUE THREAD

**Issue by Taehyeon-Kim** [TeamDooRiBon/DooRi-iOS#7]
# 👀 이슈 (issue)

프로젝트 내에서 사용할 폰트를 추가하고자 함
<img width="691" alt="스크린샷 2021-07-01 오후 8 25 56" src="https://user-images.githubusercontent.com/61109660/124116998-90965980-daaa-11eb-9299-9fe45426bbb0.png">

# 🚀 to-do

- [x] 폰트파일 프로젝트 내에 추가
- [x] info.plist 설정
- [x] 폰트 익스텐션 설정
