### ISSUE TITLE
[FEAT] 메인뷰 UI 구현

### ISSUE THREAD

**Issue by mini-min** [TeamDooRiBon/DooRi-iOS#8]
# 👀 이슈 (issue)

두리번의 메인 뷰 UI를 구현했습니다.
<img width="178" alt="스크린샷 2021-07-01 오후 8 35 04" src="https://user-images.githubusercontent.com/69389288/124118038-d43d9300-daab-11eb-9e4e-17bde4e6099c.png">

# 🚀 to-do

- [x] 진행중인 여행
- [x] 여행 추가 버튼
- [x] 다가오는 여행 리스트
- [x] 여행 시작하기 버튼
- [x] 여행 생성하기 버튼
- [x] 여행 참여하기 버튼
