### ISSUE TITLE
[FEAT] 참여코드 입력 뷰 서버 연결

### ISSUE THREAD

**Issue by Taehyeon-Kim** [TeamDooRiBon/DooRi-iOS#81]
# 👀 이슈 (issue)
참여코드 입력 뷰에 대한 서버 연결을 진행합니다.
- URI Path: http://13.209.82.176:5000/travel/group/:inviteCode
<img width="250" alt="스크린샷 2021-07-13 오후 3 46 26" src="https://user-images.githubusercontent.com/61109660/125404439-9452a600-e3f1-11eb-8ef2-1a218423338b.png">

# 🚀 to-do

- [x] 참여코드 숫자+문자 입력 가능하도록 UI 수정
- [x] 참여코드 6자리 뽑아내기 (`string`형태로)
- [x] `모두 입력해주세요` 버튼 클릭 시 API 요청
