### ISSUE TITLE
[FEAT] 여행일정뷰 특정 날짜 데이터 받아오는 API 연결

### ISSUE THREAD

**Issue by Taehyeon-Kim** [TeamDooRiBon/DooRi-iOS#83]
# 👀 이슈 (issue)
여행일정뷰에서 특정 날짜 데이터를 받아오는 API를 연결합니다.
<img width="250" alt="스크린샷 2021-07-13 오후 8 59 53" src="https://user-images.githubusercontent.com/61109660/125448015-d3847d3f-8483-44a3-bbfb-2c259a55554c.png">
- 날짜별로 조회해서 데이터를 저장해놓은다음 데이터를 화면에 뿌려줍니다.
# 🚀 to-do

- [x] TripGroupTestDataModel 생성 : 메인에서 데이터 넘겨주기 전에 테스트하기 위함
- [x] 특정 날짜 데이터 조회 Service 코드 생성
- [ ] 특정 날짜 데이터 조회 테스트
