### ISSUE TITLE
[FIX] 답변 선택화면 오류 해결

### ISSUE THREAD

**Issue by mini-min** [TeamDooRiBon/DooRi-iOS#89]
# 👀 이슈 (issue)

혜진누나가 주신 미션을 해결해보겠습니다.

# 🚀 to-do

- [x] 답변을 선택했을 때만 다음 문항으로 넘어갈 수 있도록 하기 
    - [x] 다음 문항 버튼 enable 변경
    - [x] 다음 문항 버튼 터치 불가할 때 색 변경
- [x] answer 배열에 점수 더하도록 하기
- [x] PopupView 공통 코드로 변경
- [x] indicator 로직 변경
